
###
GET http://127.0.0.1:8000/todoapp/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDA4NDQ4LCJpYXQiOjE3MTk0MDgxNDgsImp0aSI6IjNhOGEzODI1OWU3MTQzNjdiYmRlN2EzNWY5MjY5NWRhIiwidXNlcl9pZCI6NX0.Y8CZ2r5qQ8M6NNMOLIaznXXGLylQD1gi1E3l4jJE5Vk

###
GET http://127.0.0.1:8000/todoapp/todos/download
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDAyOTg2LCJpYXQiOjE3MTk0MDI2ODYsImp0aSI6IjNjZTIwMDlkNzA4MTRmODBiYjNhNGQ0MmQ3OWM0ZWYyIiwidXNlcl9pZCI6MX0.8vGI_XmkCkyPpuweMgbojs7YXORfZ6X6b60qcJEcelQ###
###



###
POST http://127.0.0.1:8000/todoapp/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###

###
POST http://127.0.0.1:8000/todoapp/api/token/
Content-Type: application/json

{
  "username": "testuser_2",
  "password": "password"
}
###

//{
//  "username": "testuser_2",
//  "password": "password"
//}