### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

###


###
GET http://127.0.0.1:8000/todoapp/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDAyMDM4LCJpYXQiOjE3MTk0MDE3MzgsImp0aSI6ImZiYmJhOGQ5NWUwZjQ2MWJiMjhiZjVkZmJlMGY2YjkwIiwidXNlcl9pZCI6MX0.gntruYTxp0iEzWO25mIroE4E2aMhtGOyd5uOECvp2Jk
###

###
POST http://127.0.0.1:8000/todoapp/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###