
###
#GET http://127.0.0.1:8000/todoapp/todos/?priority=L
GET http://127.0.0.1:8000/todoapp/todos/?title=C
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDEyNTY1LCJpYXQiOjE3MTk0MDg5NjUsImp0aSI6IjZlMTM2NDA1YTU3YTQwYzFiYmIzMjA5ZjNlNzVjMmQ0IiwidXNlcl9pZCI6NX0.KNao6dG8k5RDA4UucESpXU0E8dh2iXRGrSbYRjmCyxs
###
GET http://127.0.0.1:8000/todoapp/todos/download
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDAyOTg2LCJpYXQiOjE3MTk0MDI2ODYsImp0aSI6IjNjZTIwMDlkNzA4MTRmODBiYjNhNGQ0MmQ3OWM0ZWYyIiwidXNlcl9pZCI6MX0.8vGI_XmkCkyPpuweMgbojs7YXORfZ6X6b60qcJEcelQ###
###



###
POST http://127.0.0.1:8000/todoapp/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###

###
POST http://127.0.0.1:8000/todoapp/api/token/
Content-Type: application/json

{
  "username": "testuser_2",
  "password": "password"
}
###

//{
//  "username": "testuser_2",
//  "password": "password"
//}